server:
    port: 9500
    
spring:
    application:
        name: services-auth
    
    redis:
        host: graceyu.top
        port: 6379
        password: Graceyu9898963
        database: 0
        jedis:
            pool:
                max-active: 50
                max-wait: 3000
                max-idle: 20
                min-idle: 2
        timeout: 5000
