server:
    port: 9100
    
    
#eureka:
#    instance:
#        hostname: localhost
#    client:
#        service-url:
#            defaultZone: http://${eureka.instance.hostname}:8100/eureka/

spring:
    application:
        name: services-auth
    
    datasource:
        url: jdbc:mysql://graceyu.top:3306/falleaves
        username: falleaves
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            auto-commit: true
            minimum-idle: 2
            idle-timeout: 60000
            connection-timeout: 10000
            max-lifetime: 1800000
            pool-name: AuthHikariCP
            maximum-pool-size: 5
    jpa:
        database: mysql
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
            
    redis:
        host: graceyu.top
        port: 6379
        password: Graceyu9898963
        database: 0
        jedis:
            pool:
                max-active: 50
                max-wait: 3000
                max-idle: 20
                min-idle: 2
        timeout: 5000
