server:
    port: 8200

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://${eureka.instance.hostname}:8100/eureka/
        
zuul:
    routes:
        auth:
            path: /auth/**
            serviceId: services-auth
        mail:
            path: /mail/**
            serviceId: services-mail

